---
resources:
  - name: pks-demo-git-repo
    type: git
    source:
      uri: https://github.com/hemanth-avs/pks-demo.git
      branch: master

jobs:
  - name: job-list-files
    public: true
    plan:
      - get: pks-demo-git-repo
        trigger: true
      - task: list-files
        file: pks-demo-git-repo/ci/concourse/tasks/list-files.yml
      - task: unit-test
        file: pks-demo-git-repo/ci/concourse/tasks/mvn-test.yml
      - task: package
        file: pks-demo-git-repo/ci/concourse/tasks/mvn-package.yml