---
resources:
  - name: pks-demo-git-repo
    type: git
    source:
      uri: https://github.com/hemanth-avs/pks-demo.git
      branch: master
  - name: pks-demo-helm-git-repo
    type: git
    source:
      uri: https://github.com/hemanth-avs/pks-demo.git
      branch: master
      disable_ci_skip: true
  - name: pks-demo-image
    type: docker-image
    source:
      repository: harbor.caas.pez.pivotal.io:443/hemanth/pks-demo
      insecure_registries: [ "harbor.caas.pez.pivotal.io:443" ]
      username: ((harbor-username))
      password: ((harbor-password))
  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:hemanth-avs/pks-demo.git
      branch: master
      file: version
      commit_message: "ci skip"
      private_key: ((GIT_PRIVATE_KEY))
jobs:
  - name: unit-tests
    public: true
    plan:
      - get: pks-demo-git-repo
        trigger: true
      #- task: list-files
      #  file: pks-demo-git-repo/ci/concourse/tasks/list-files.yml
      - task: unit-test
        file: pks-demo-git-repo/ci/concourse/tasks/mvn-test.yml
      - task: package
        file: pks-demo-git-repo/ci/concourse/tasks/mvn-package.yml
  - name: build-artifact
    public: true
    serial: true
    plan:
    - get: version
    - put: version
      params: {bump: patch}
    - get: pks-demo-git-repo
      passed: [unit-tests]
      trigger: true
    - put: pks-demo-image
      params: { build: pks-demo-git-repo, tag_file: version/version }
  - name: deploy-pks
    public: true
    plan:
      - get: pks-demo-helm-git-repo
        trigger: true
      - task: deploy-pks-app
        file: pks-demo-helm-git-repo/ci/concourse/tasks/deploy-demo-app.yml
        params:
          PKS_API: ((PKS_API))
          PKS_CLI_USERNAME: ((PKS_CLI_USERNAME))
          PKS_CLI_PASSWORD: ((PKS_CLI_PASSWORD))
          PKS_CLUSTER_NAME: ((PKS_CLUSTER_NAME))
          PKS_SKIP_TLS_VERIFY: true
# sed -i 's/STRING_TO_REPLACE/STRING_TO_REPLACE_IT/g' filename
