---
resources:
  - name: resource-git-pks-demo
    type: git
    source:
      uri: https://github.com/hemanth-avs/pks-demo.git
      branch: master

jobs:
  - name: job-list-files
    public: true
    plan:
      - get: resource-git-pks-demo
        trigger: true
      - task: list-files
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          inputs:
            - name: resource-git-pks-demo
              path: code
          run:        
            path: ./code/ci/concourse/config/list-files.sh
            #path: ls
            #args: [-lRrta]
            # ./mvnw test
      - task: unit-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          inputs:
            - name: resource-git-pks-demo
              path: code
          run:
            path: ./mvnw
            args: [ test ]