---
resources:

  - name: articulate-repo
    type: git
    source:
      uri: https://github.com/hemanth-avs/pks-demo.git
      branch: master
      disable_ci_skip: false
  
  - name: articulate-helmchart
    type: git
    source:
      uri: https://github.com/Pivotal-Field-Engineering/articulate-helmchart.git
      branch: master
      disable_ci_skip: true
  
  - name: articulate-image
    type: docker-image
    source:
      repository: harbor.caas.pez.pivotal.io:443/hemanth/pks-demo
      insecure_registries: [ "harbor.caas.pez.pivotal.io:443" ]
      username: ((harbor-username))
      password: ((harbor-password))
  
  - name: helmchart-semver
    type: semver
    source:
      driver: git
      uri: git@github.com:Pivotal-Field-Engineering/articulate-helmchart.git
      branch: master
      file: articulate/version
      commit_message: "ci skip"
      private_key: ((GIT_PRIVATE_KEY))

jobs:
  - name: unit-test
    public: true
    plan:
      - get: articulate-repo
        trigger: true
      - task: unit-test
        file: articulate-repo/ci/concourse/tasks/mvn-test.yml
  
  - name: publish-image
    public: true
    serial: true
    plan:
    - get: articulate-repo
      passed: [unit-test]
      trigger: true
    - get: helmchart-semver
    - put: articulate-image
      params: { build: articulate-repo, tag_file: helmchart-semver/version }
    - put: helmchart-semver
      params: {bump: patch}

  - name: deploy-articulate
    public: true
    plan:
      - get: articulate-repo
      - get: articulate-helmchart
        trigger: true
      - task: deploy-articulate-app
        file: articulate-repo/ci/concourse/tasks/deploy-demo-app.yml
        params:
          PKS_API: ((PKS_API))
          PKS_CLI_USERNAME: ((PKS_CLI_USERNAME))
          PKS_CLI_PASSWORD: ((PKS_CLI_PASSWORD))
          PKS_CLUSTER_NAME: ((PKS_CLUSTER_NAME))
          PKS_SKIP_TLS_VERIFY: true
