---
resources:
  - name: pks-demo-git-repo
    type: git
    source:
      uri: https://github.com/hemanth-avs/pks-demo.git
      branch: master
  - name: pks-demo-image
    type: docker-image
    source:
      repository: harbor.caas.pez.pivotal.io:443/hemanth/pks-demo
      insecure_registries: [ "harbor.caas.pez.pivotal.io:443" ]
      username: ((harbor-username))
      password: ((harbor-password))
  - name: pcf-pipelines-utils
    type: git
    source:
      uri: https://github.com/pivotalservices/concourse-pipeline-samples.git

jobs:
  - name: unit-tests
    public: true
    plan:
      - get: pks-demo-git-repo
        trigger: true
      #- task: list-files
      #  file: pks-demo-git-repo/ci/concourse/tasks/list-files.yml
      - task: unit-test
        file: pks-demo-git-repo/ci/concourse/tasks/mvn-test.yml
      - task: package
        file: pks-demo-git-repo/ci/concourse/tasks/mvn-package.yml
  - name: build-artifact
    public: true
    serial: true
    plan:
    - get: pks-demo-git-repo
      passed: [unit-tests]
      trigger: true
    - put: pks-demo-image
      params: { build: pks-demo-git-repo, tag_as_latest: true }


jobs:
  - name: deploy-pks
    public: true
    plan:
      - get: pcf-pipelines-utils
      - get: pks-demo-image
        trigger: true
      - task: deploy-pks-app
        file: pks-demo-git-repo/ci/concourse/tasks/deploy-demo-app.yml
      - task: package
        file: pks-demo-git-repo/ci/concourse/tasks/mvn-package.yml