NAME: pks-demo-1584588013
LAST DEPLOYED: Wed Mar 18 22:20:15 2020
NAMESPACE: default
STATUS: pending-install
REVISION: 1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: harbor.caas.pez.pivotal.io/hemanth/pks-demo
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: pks-demo.local
    paths: []
  tls: []
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 8080
  type: ClusterIP
serviceAccount:
  create: true
  name: null
tolerations: []

HOOKS:
---
# Source: pks-demo/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "pks-demo-1584588013-test-connection"
  labels:

    helm.sh/chart: pks-demo-0.1.0
    app.kubernetes.io/name: pks-demo
    app.kubernetes.io/instance: pks-demo-1584588013
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['pks-demo-1584588013:8080']
  restartPolicy: Never
MANIFEST:
---
# Source: pks-demo/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pks-demo-1584588013
  labels:

    helm.sh/chart: pks-demo-0.1.0
    app.kubernetes.io/name: pks-demo
    app.kubernetes.io/instance: pks-demo-1584588013
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: pks-demo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pks-demo-1584588013
  labels:
    helm.sh/chart: pks-demo-0.1.0
    app.kubernetes.io/name: pks-demo
    app.kubernetes.io/instance: pks-demo-1584588013
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pks-demo
    app.kubernetes.io/instance: pks-demo-1584588013
---
# Source: pks-demo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pks-demo-1584588013
  labels:
    helm.sh/chart: pks-demo-0.1.0
    app.kubernetes.io/name: pks-demo
    app.kubernetes.io/instance: pks-demo-1584588013
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pks-demo
      app.kubernetes.io/instance: pks-demo-1584588013
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pks-demo
        app.kubernetes.io/instance: pks-demo-1584588013
    spec:
      serviceAccountName: pks-demo-1584588013
      securityContext:
        {}
      containers:
        - name: pks-demo
          securityContext:
            {}
          image: "harbor.caas.pez.pivotal.io/hemanth/pks-demo:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=pks-demo,app.kubernetes.io/instance=pks-demo-1584588013" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:80
