---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}
inputs:
  - name: resource-git-pks-demo
    path: code
run:        
  path: ./code/ci/concourse/config/list-files.sh
#run:
#  dir: code
#  path: ls
#  args: ["-lRta"]